// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: critic_reviews.sql

package db

import (
	"context"
)

const createCriticReview = `-- name: CreateCriticReview :one
INSERT INTO critic_reviews (
    id,
    session_id,
    message_id,
    verdict,
    confidence,
    concerns,
    summary,
    diff_snapshot,
    lsp_diagnostics,
    created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now')
)
RETURNING id, session_id, message_id, verdict, confidence, concerns, summary, diff_snapshot, lsp_diagnostics, created_at, revision_outcome
`

type CreateCriticReviewParams struct {
	ID             string  `json:"id"`
	SessionID      string  `json:"session_id"`
	MessageID      string  `json:"message_id"`
	Verdict        string  `json:"verdict"`
	Confidence     float64 `json:"confidence"`
	Concerns       string  `json:"concerns"`
	Summary        string  `json:"summary"`
	DiffSnapshot   string  `json:"diff_snapshot"`
	LspDiagnostics string  `json:"lsp_diagnostics"`
}

func (q *Queries) CreateCriticReview(ctx context.Context, arg CreateCriticReviewParams) (CriticReview, error) {
	row := q.queryRow(ctx, q.createCriticReviewStmt, createCriticReview,
		arg.ID,
		arg.SessionID,
		arg.MessageID,
		arg.Verdict,
		arg.Confidence,
		arg.Concerns,
		arg.Summary,
		arg.DiffSnapshot,
		arg.LspDiagnostics,
	)
	var i CriticReview
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.Verdict,
		&i.Confidence,
		&i.Concerns,
		&i.Summary,
		&i.DiffSnapshot,
		&i.LspDiagnostics,
		&i.CreatedAt,
		&i.RevisionOutcome,
	)
	return i, err
}

const getCriticReviewByMessageID = `-- name: GetCriticReviewByMessageID :one
;

SELECT id, session_id, message_id, verdict, confidence, concerns, summary, diff_snapshot, lsp_diagnostics, created_at, revision_outcome
FROM critic_reviews
WHERE message_id = ? LIMIT 1
`

func (q *Queries) GetCriticReviewByMessageID(ctx context.Context, messageID string) (CriticReview, error) {
	row := q.queryRow(ctx, q.getCriticReviewByMessageIDStmt, getCriticReviewByMessageID, messageID)
	var i CriticReview
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.Verdict,
		&i.Confidence,
		&i.Concerns,
		&i.Summary,
		&i.DiffSnapshot,
		&i.LspDiagnostics,
		&i.CreatedAt,
		&i.RevisionOutcome,
	)
	return i, err
}

const listCriticReviewsBySession = `-- name: ListCriticReviewsBySession :many
;

SELECT id, session_id, message_id, verdict, confidence, concerns, summary, diff_snapshot, lsp_diagnostics, created_at, revision_outcome
FROM critic_reviews
WHERE session_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListCriticReviewsBySession(ctx context.Context, sessionID string) ([]CriticReview, error) {
	rows, err := q.query(ctx, q.listCriticReviewsBySessionStmt, listCriticReviewsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CriticReview{}
	for rows.Next() {
		var i CriticReview
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MessageID,
			&i.Verdict,
			&i.Confidence,
			&i.Concerns,
			&i.Summary,
			&i.DiffSnapshot,
			&i.LspDiagnostics,
			&i.CreatedAt,
			&i.RevisionOutcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneCriticReviews = `-- name: PruneCriticReviews :execrows
;

DELETE FROM critic_reviews
WHERE created_at < ?
`

func (q *Queries) PruneCriticReviews(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.exec(ctx, q.pruneCriticReviewsStmt, pruneCriticReviews, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
