// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type CriticReview struct {
	ID              string  `json:"id"`
	SessionID       string  `json:"session_id"`
	MessageID       string  `json:"message_id"`
	Verdict         string  `json:"verdict"`
	Confidence      float64 `json:"confidence"`
	Concerns        string  `json:"concerns"`
	Summary         string  `json:"summary"`
	DiffSnapshot    string  `json:"diff_snapshot"`
	LspDiagnostics  string  `json:"lsp_diagnostics"`
	CreatedAt       int64   `json:"created_at"`
	RevisionOutcome string  `json:"revision_outcome"`
}

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Message struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	Role             string         `json:"role"`
	Parts            string         `json:"parts"`
	Model            sql.NullString `json:"model"`
	CreatedAt        int64          `json:"created_at"`
	UpdatedAt        int64          `json:"updated_at"`
	FinishedAt       sql.NullInt64  `json:"finished_at"`
	Provider         sql.NullString `json:"provider"`
	IsSummaryMessage int64          `json:"is_summary_message"`
}

type ReadFile struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	ReadAt    int64  `json:"read_at"`
}

type Session struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	Todos            sql.NullString `json:"todos"`
}

type ToolcoachEffectiveness struct {
	ID           int64  `json:"id"`
	PatternID    string `json:"pattern_id"`
	SessionID    string `json:"session_id"`
	FiredCount   int64  `json:"fired_count"`
	ActedCount   int64  `json:"acted_count"`
	IgnoredCount int64  `json:"ignored_count"`
	CreatedAt    int64  `json:"created_at"`
}

type WrittenFile struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	WrittenAt int64  `json:"written_at"`
}
