// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: toolcoach_effectiveness.sql

package db

import (
	"context"
	"database/sql"
)

const createToolcoachEffectiveness = `-- name: CreateToolcoachEffectiveness :one
INSERT INTO toolcoach_effectiveness (
    pattern_id,
    session_id,
    fired_count,
    acted_count,
    ignored_count,
    created_at
) VALUES (
    ?, ?, ?, ?, ?, strftime('%s', 'now')
)
RETURNING id, pattern_id, session_id, fired_count, acted_count, ignored_count, created_at
`

type CreateToolcoachEffectivenessParams struct {
	PatternID    string `json:"pattern_id"`
	SessionID    string `json:"session_id"`
	FiredCount   int64  `json:"fired_count"`
	ActedCount   int64  `json:"acted_count"`
	IgnoredCount int64  `json:"ignored_count"`
}

func (q *Queries) CreateToolcoachEffectiveness(ctx context.Context, arg CreateToolcoachEffectivenessParams) (ToolcoachEffectiveness, error) {
	row := q.queryRow(ctx, q.createToolcoachEffectivenessStmt, createToolcoachEffectiveness,
		arg.PatternID,
		arg.SessionID,
		arg.FiredCount,
		arg.ActedCount,
		arg.IgnoredCount,
	)
	var i ToolcoachEffectiveness
	err := row.Scan(
		&i.ID,
		&i.PatternID,
		&i.SessionID,
		&i.FiredCount,
		&i.ActedCount,
		&i.IgnoredCount,
		&i.CreatedAt,
	)
	return i, err
}

const getToolcoachEffectivenessByPattern = `-- name: GetToolcoachEffectivenessByPattern :many
;

SELECT pattern_id, SUM(fired_count) AS total_fired, SUM(acted_count) AS total_acted, SUM(ignored_count) AS total_ignored
FROM toolcoach_effectiveness
WHERE pattern_id = ? AND created_at > ?
GROUP BY pattern_id
`

type GetToolcoachEffectivenessByPatternParams struct {
	PatternID string `json:"pattern_id"`
	CreatedAt int64  `json:"created_at"`
}

type GetToolcoachEffectivenessByPatternRow struct {
	PatternID    string          `json:"pattern_id"`
	TotalFired   sql.NullFloat64 `json:"total_fired"`
	TotalActed   sql.NullFloat64 `json:"total_acted"`
	TotalIgnored sql.NullFloat64 `json:"total_ignored"`
}

func (q *Queries) GetToolcoachEffectivenessByPattern(ctx context.Context, arg GetToolcoachEffectivenessByPatternParams) ([]GetToolcoachEffectivenessByPatternRow, error) {
	rows, err := q.query(ctx, q.getToolcoachEffectivenessByPatternStmt, getToolcoachEffectivenessByPattern, arg.PatternID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetToolcoachEffectivenessByPatternRow{}
	for rows.Next() {
		var i GetToolcoachEffectivenessByPatternRow
		if err := rows.Scan(
			&i.PatternID,
			&i.TotalFired,
			&i.TotalActed,
			&i.TotalIgnored,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneToolcoachEffectiveness = `-- name: PruneToolcoachEffectiveness :execrows
;

DELETE FROM toolcoach_effectiveness
WHERE created_at < ?
`

func (q *Queries) PruneToolcoachEffectiveness(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.exec(ctx, q.pruneToolcoachEffectivenessStmt, pruneToolcoachEffectiveness, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
